### ISSUE TITLE
PYYaml version requirement and Cython conflict

### ISSUE THREAD

**Issue by avalluvan** [cositools/cosi-sim#65]
Posting here for completeness,
While setting up the python environment (or when invoked during `cosi-setup` setup), pyyaml may not install due to a known Cython conflict (See https://github.com/yaml/pyyaml/issues/601, seems to be a MacOS issue). I have attached a screenshot below:
<img width="646" alt="image" src="https://github.com/cositools/cosi-data-challenges/assets/62253557/e9a0ca65-de02-480e-871a-8d8b4fdfe389">
```
Using cached pandas-1.4.2-cp38-cp38-macosx_11_0_arm64.whl.metadata (12 kB)
Collecting pyyaml==6.0 (from -r /tmp/cositoolsrequirementsfile.YCBo68IbZ (line 2))
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
```
Modifying the requirements.txt file associated with the repository cosi-data-challenges from 6.0 to 6.0.1 worked for me.

**Comment by ckarwin** [comment]
Thanks for bringing this up @avalluvan. How are you installing this repository? Is it being installed as part of the COSITools install?

**Comment by avalluvan** [comment]
Yes. I have posted a complementary issue on the cosi-setup repository too, that redirects to this issue.

**Comment by ckarwin** [comment]
Ok, thanks. I'll take a look, and probably the simple update you suggested should be fine.

**Comment by ckarwin** [comment]
I updated requirements.txt. That should resolve this issue.
